# Generated by Django 3.1.5 on 2021-01-28 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('rut', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.IntegerField()),
                ('fechaN', models.DateField()),
                ('usuario', models.CharField(max_length=12)),
                ('contraseña', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Habitacion',
            fields=[
                ('nHabitacion', models.IntegerField(primary_key=True, serialize=False)),
                ('tipoHabitacion', models.CharField(max_length=20)),
                ('metroCuadrado', models.IntegerField()),
                ('baños', models.IntegerField()),
                ('camas', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('diasReservados', models.IntegerField()),
                ('fechaReserva', models.DateField()),
                ('nHabitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.habitacion')),
                ('rutCliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.cliente')),
            ],
        ),
    ]
